name: build

on:
  push:
    branches:
      - 'github-actions' # remove when merged to master
      - 'master'
      - 'v*'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'github-actions' # remove when merged to master
      - 'master'
      - 'v*'

env:
  BUILDKIT_VERSION: "v0.7.0-rc1"
  REPO_SLUG_TARGET: "moby/buildkit"
  PLATFORMS: "linux/amd64,linux/arm/v7,linux/arm64,linux/s390x,linux/ppc64le"

jobs:
  binaries:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: image=moby/buildkit:${{ env.BUILDKIT_VERSION }}
      -
        name: Cache binaries
        uses: actions/cache@v2
        with:
          path: /tmp/.buildkit-cache/binaries
          key: ${{ runner.os }}-buildkit-binaries-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildkit-binaries-
      -
        name: Build binaries
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          target: binaries
          cache-from: type=local,src=/tmp/.buildkit-cache/binaries
          cache-to: type=local,dest=/tmp/.buildkit-cache/binaries
      -
        name: Dump context
        if: always()
        uses: crazy-max/ghaction-dump-context@v1

  binaries-cross-helper:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: image=moby/buildkit:${{ env.BUILDKIT_VERSION }}
      -
        name: Cache binaries-cross-helper
        uses: actions/cache@v2
        with:
          path: /tmp/.buildkit-cache/binaries-cross-helper
          key: ${{ runner.os }}-buildkit-binaries-cross-helper-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildkit-binaries-cross-helper-
      -
        name: Build binaries-cross-helper
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          target: binaries-linux-helper
          platforms: ${{ env.PLATFORMS }}
          cache-from: type=local,src=/tmp/.buildkit-cache/binaries-cross-helper
          cache-to: type=local,dest=/tmp/.buildkit-cache/binaries-cross-helper
      -
        name: Dump context
        if: always()
        uses: crazy-max/ghaction-dump-context@v1

  cross:
    runs-on: ubuntu-latest
    needs: [ binaries-cross-helper ]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: image=moby/buildkit:${{ env.BUILDKIT_VERSION }}
      -
        name: Cache binaries-cross-helper
        uses: actions/cache@v2
        with:
          path: /tmp/.buildkit-cache/binaries-cross-helper
          key: ${{ runner.os }}-buildkit-binaries-cross-helper-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildkit-binaries-cross-helper-
      -
        name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{ env.PLATFORMS }},darwin/amd64,windows/amd64
          cache-from: type=local,src=/tmp/.buildkit-cache/binaries-cross-helper
      -
        name: Dump context
        if: always()
        uses: crazy-max/ghaction-dump-context@v1

  buildkit-buildkitd:
    runs-on: ubuntu-latest
    needs: [ binaries ]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: image=moby/buildkit:${{ env.BUILDKIT_VERSION }}
      -
        name: Cache binaries
        uses: actions/cache@v2
        with:
          path: /tmp/.buildkit-cache/binaries
          key: ${{ runner.os }}-buildkit-binaries-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildkit-binaries-
      -
        name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          target: buildkit-buildkitd
          platforms: windows/amd64
          cache-from: type=local,src=/tmp/.buildkit-cache/binaries
      -
        name: Dump context
        if: always()
        uses: crazy-max/ghaction-dump-context@v1

  install:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          #- macOS-latest
          - windows-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          path: src/github.com/moby/buildkit
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.13
      -
        name: Cache Go modules
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      -
        name: Install
        env:
          TMPDIR: ${{ runner.temp }}
        run: |
          go install -mod=vendor ./cmd/...
        working-directory: src/github.com/moby/buildkit
        shell: bash
      -
        name: Dump context
        if: always()
        uses: crazy-max/ghaction-dump-context@v1
