name: lint

on:
  push:
    branches:
      - 'github-actions' # remove when merged to master
      - 'master'
      - 'v*'
    tags:
      - 'v*'
      - 'dockerfile/*'
  pull_request:
    branches:
      - 'github-actions' # remove when merged to master
      - 'master'
      - 'v*'

env:
  BUILDKIT_VERSION: "v0.7.0-rc1"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: image=moby/buildkit:${{ env.BUILDKIT_VERSION }}
      -
        name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./hack/dockerfiles/lint.Dockerfile
      -
        name: Dump context
        if: always()
        uses: crazy-max/ghaction-dump-context@v1

  validate-vendor:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: image=moby/buildkit:${{ env.BUILDKIT_VERSION }}
      -
        name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./hack/dockerfiles/vendor.Dockerfile
          target: validate
      -
        name: Dump context
        if: always()
        uses: crazy-max/ghaction-dump-context@v1

  validate-generated-files:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: image=moby/buildkit:${{ env.BUILDKIT_VERSION }}
      -
        name: Extract protobuf version
        id: protobuf
        run: |
          echo ::set-output name=version::$(awk '$1 == "github.com/gogo/protobuf" { print $2 }' go.mod)
      -
        name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./hack/dockerfiles/generated-files.Dockerfile
          target: validate
          build-args: |
            GOGO_VERSION=${{ steps.protobuf.outputs.version }}
      -
        name: Dump context
        if: always()
        uses: crazy-max/ghaction-dump-context@v1

  validate-shfmt:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: image=moby/buildkit:${{ env.BUILDKIT_VERSION }}
      -
        name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./hack/dockerfiles/shfmt.Dockerfile
          target: validate
      -
        name: Dump context
        if: always()
        uses: crazy-max/ghaction-dump-context@v1
