name: lint

on:
  push:
    branches:
      - 'github-actions' # remove when merged to master
      - 'master'
      - 'v*'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'github-actions' # remove when merged to master
      - 'master'
      - 'v*'

env:
  REPO_SLUG_ORIGIN: "moby/buildkit"
  LINUXKIT_BINFMT: "v0.8"
  BUILDKIT_HOST: "tcp://0.0.0.0:1234"
  BUILDKIT_PORT: "1234"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Install buildctl
        run: |
          mkdir -p /tmp/buildctl
          docker run --rm --privileged linuxkit/binfmt:$LINUXKIT_BINFMT
          docker run --name buildkit -d --privileged -p $BUILDKIT_PORT:$BUILDKIT_PORT $REPO_SLUG_ORIGIN --debug --addr $BUILDKIT_HOST --oci-worker-gc=false
          sudo docker cp buildkit:/usr/bin/buildctl /usr/local/bin/
      -
        name: Build
        run: |
          buildctl build --frontend=dockerfile.v0 \
            --local context=. --local dockerfile=. \
            --opt filename=./hack/dockerfiles/lint.Dockerfile
      -
        name: Dump context
        if: always()
        uses: crazy-max/ghaction-dump-context@v1

  validate-vendor:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Install buildctl
        run: |
          mkdir -p /tmp/buildctl
          docker run --rm --privileged linuxkit/binfmt:$LINUXKIT_BINFMT
          docker run --name buildkit -d --privileged -p $BUILDKIT_PORT:$BUILDKIT_PORT $REPO_SLUG_ORIGIN --debug --addr $BUILDKIT_HOST --oci-worker-gc=false
          sudo docker cp buildkit:/usr/bin/buildctl /usr/local/bin/
      -
        name: Build
        run: |
          buildctl build --frontend=dockerfile.v0 \
            --local context=. --local dockerfile=. \
            --opt filename=./hack/dockerfiles/vendor.Dockerfile \
            --opt target=validate
      -
        name: Dump context
        if: always()
        uses: crazy-max/ghaction-dump-context@v1

  validate-generated-files:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Install buildctl
        run: |
          mkdir -p /tmp/buildctl
          docker run --rm --privileged linuxkit/binfmt:$LINUXKIT_BINFMT
          docker run --name buildkit -d --privileged -p $BUILDKIT_PORT:$BUILDKIT_PORT $REPO_SLUG_ORIGIN --debug --addr $BUILDKIT_HOST --oci-worker-gc=false
          sudo docker cp buildkit:/usr/bin/buildctl /usr/local/bin/
      -
        name: Build
        run: |
          gogo_version=$(awk '$1 == "github.com/gogo/protobuf" { print $2 }' go.mod)
          buildctl build --frontend=dockerfile.v0 \
            --local context=. --local dockerfile=. \
            --opt build-arg:GOGO_VERSION=$gogo_version \
            --opt filename=./hack/dockerfiles/generated-files.Dockerfile \
            --opt target=validate
      -
        name: Dump context
        if: always()
        uses: crazy-max/ghaction-dump-context@v1

  validate-shfmt:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Install buildctl
        run: |
          mkdir -p /tmp/buildctl
          docker run --rm --privileged linuxkit/binfmt:$LINUXKIT_BINFMT
          docker run --name buildkit -d --privileged -p $BUILDKIT_PORT:$BUILDKIT_PORT $REPO_SLUG_ORIGIN --debug --addr $BUILDKIT_HOST --oci-worker-gc=false
          sudo docker cp buildkit:/usr/bin/buildctl /usr/local/bin/
      -
        name: Build
        run: |
          buildctl build --frontend=dockerfile.v0 \
            --local context=. --local dockerfile=. \
            --opt filename=./hack/dockerfiles/shfmt.Dockerfile \
            --opt target=validate
      -
        name: Dump context
        if: always()
        uses: crazy-max/ghaction-dump-context@v1
