name: release

on:
  push:
    branches:
      - 'github-actions' # remove when merged to master
      - 'master'
      - 'v*'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'github-actions' # remove when merged to master
      - 'master'
      - 'v*'

env:
  BUILDKIT_VERSION: "v0.7.0-rc1"
  REPO_SLUG_TARGET: "moby/buildkit"
  PLATFORMS: "linux/amd64,linux/arm/v7,linux/arm64,linux/s390x,linux/ppc64le"

jobs:
  docker-image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target-stage:
          - ""
          - rootless
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Prepare
        id: prep
        run: |
          VERSION=local
          if [ "${{ github.event_name }}" = "schedule" ]; then
            VERSION=nightly
          elif [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          elif [[ $GITHUB_REF == refs/heads/* ]]; then
            VERSION=$(echo ${GITHUB_REF#refs/heads/} | sed -r 's#/+#-#g')
          fi
          if [ "${{ matrix.target-stage }}" != "" ]; then
            MAIN_TAG=${{ matrix.target-stage }}
            TAGS="${REPO_SLUG_TARGET}:${VERSION}-${{ matrix.target-stage }}"
          else
            MAIN_TAG=latest
            TAGS="${REPO_SLUG_TARGET}:${VERSION}"
          fi
          if [[ $VERSION =~ ^v[0-9]{1,3}\.[0-9]{1,3} ]]; then
            if [ "${{ matrix.target-stage }}" != "" ]; then
              TAGS="$TAGS,${REPO_SLUG_TARGET}:${{ matrix.target-stage }}"
            else
              TAGS="$TAGS,${REPO_SLUG_TARGET}:latest"
            fi
          fi
          echo ::set-output name=version::${VERSION}
          echo ::set-output name=tags::${TAGS}
          echo ::set-output name=created::$(date -u +'%Y-%m-%dT%H:%M:%SZ')
          echo ::set-output name=platforms::${PLATFORMS}
          echo ::set-output name=main_tag::${MAIN_TAG}
      -
        name: Repo metadata
        id: repo
        uses: actions/github-script@v3
        with:
          script: |
            const repo = await github.repos.get(context.repo)
            return repo.data
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: image=moby/buildkit:${{ env.BUILDKIT_VERSION }}
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        if: github.event_name != 'pull_request'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          target: ${{ matrix.target-stage }}
          platforms: ${{ env.PLATFORMS }}
          push: ${{ github.event_name != 'pull_request' }}
          cache-from: type=registry,ref=${{ env.REPO_SLUG_TARGET }}:${{ steps.prep.outputs.main_tag }}
          #cache-to: type=inline
          tags: ${{ steps.prep.outputs.tags }}
          labels: |
            org.opencontainers.image.title=${{ fromJson(steps.repo.outputs.result).name }}
            org.opencontainers.image.url=${{ fromJson(steps.repo.outputs.result).html_url }}
            org.opencontainers.image.source=${{ fromJson(steps.repo.outputs.result).clone_url }}
            org.opencontainers.image.version=${{ steps.prep.outputs.version }}
            org.opencontainers.image.created=${{ steps.prep.outputs.created }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.licenses=${{ fromJson(steps.repo.outputs.result).license.spdx_id }}
      -
        name: Check manifest
        if: github.event_name != 'pull_request' && startsWith(github.ref, 'refs/tags/v')
        run: |
          docker buildx imagetools inspect ${{ env.REPO_SLUG_TARGET }}:${{ steps.prep.outputs.main_tag }}
      -
        name: Inspect image
        if: github.event_name != 'pull_request' && startsWith(github.ref, 'refs/tags/v')
        run: |
          docker pull ${{ env.REPO_SLUG_TARGET }}:${{ steps.prep.outputs.main_tag }}
          docker image inspect ${{ env.REPO_SLUG_TARGET }}:${{ steps.prep.outputs.main_tag }}
      -
        name: Dump context
        if: always()
        uses: crazy-max/ghaction-dump-context@v1

  binaries:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: image=moby/buildkit:${{ env.BUILDKIT_VERSION }}
      -
        name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          target: release
          platforms: ${{ env.PLATFORMS }},darwin/amd64,windows/amd64
          outputs: type=local,dest=./release-out
      -
        name: Move artifacts
        run: |
          mv ./release-out/**/* ./release-out/
      -
        name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: buildkit
          path: ./release-out/*
          if-no-files-found: error
      -
        name: GitHub Release
        uses: softprops/action-gh-release@v1
        if: success() && startsWith(github.ref, 'refs/tags/v')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          files: ./release-out/*
          name: ${{ steps.prep.outputs.tag_name }}
      -
        name: Dump context
        if: always()
        uses: crazy-max/ghaction-dump-context@v1
