name: test

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
      - 'dockerfile/*'
  pull_request:
    branches:
      - 'master'

env:
  REPO_SLUG_ORIGIN: "moby/buildkit:latest"

jobs:
  test-base:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Cache integration-tests
        uses: actions/cache@v2
        with:
          path: /tmp/.buildkit-cache/integration-tests
          key: ${{ runner.os }}-buildkit-integration-tests-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildkit-integration-tests-
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: image=${{ env.REPO_SLUG_ORIGIN }}
      -
        name: Build integration-tests
        run: |
          ./hack/build_ci_first_pass integration-tests
        env:
          CACHE_REF: /tmp/.buildkit-cache/integration-tests
      -
        name: Dump context
        if: always()
        uses: crazy-max/ghaction-dump-context@v1

  test:
    runs-on: ubuntu-latest
    needs: [ test-base ]
    strategy:
      fail-fast: false
      matrix:
        include:
          -
            pkg: ./client
            flags: -v --timeout=20m
            skip-it: 0
            typ: integration
          -
            pkg: ./cmd/buildctl
            flags: -v
            skip-it: 0
            typ: integration
          -
            pkg: ./worker/containerd
            flags: -v
            skip-it: 0
            typ: integration
          -
            pkg: ''
            flags: -v
            skip-it: 1
            typ: integration gateway
          -
            pkg: ./frontend
            flags: -v
            skip-it: 0
            typ: ''
          -
            pkg: ./frontend/dockerfile
            flags: -v --parallel=6 --timeout=20m
            skip-it: 0
            typ: ''
          -
            pkg: ./frontend/dockerfile
            flags: -v
            skip-it: 0
            typ: dockerfile
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Cache integration-tests
        uses: actions/cache@v2
        with:
          path: /tmp/.buildkit-cache/integration-tests
          key: ${{ runner.os }}-buildkit-integration-tests-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildkit-integration-tests-
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: image=${{ env.REPO_SLUG_ORIGIN }}
      -
        name: Test ${{ matrix.pkg }} ${{ matrix.typ }}
        run: |
          ./hack/test ${{ matrix.typ }}
        env:
          TESTPKGS: ${{ matrix.pkg }}
          TESTFLAGS: ${{ matrix.flags }}
          SKIP_INTEGRATION_TESTS: ${{ matrix.skip-it }}
          CACHE_REF: /tmp/.buildkit-cache/integration-tests
      -
        name: Dump context
        if: always()
        uses: crazy-max/ghaction-dump-context@v1
